name: Release Github zip

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - uses: papeloto/action-zip@v1
        with:
          files: /
          dest: wp-depay-payments-plugin.zip
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: wp-depay-payments-plugin.zip
